// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return desktop;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEszlshWEkb_4xBsh4x-tJ6EHTmWh1uH0',
    appId: '1:1083041642321:web:18d420fc515dec1b844570',
    messagingSenderId: '1083041642321',
    projectId: 'my-market-4b747',
    authDomain: 'my-market-4b747.firebaseapp.com',
    storageBucket: 'my-market-4b747.appspot.com',
  );

  static const FirebaseOptions desktop = FirebaseOptions(
    apiKey: 'AIzaSyBEszlshWEkb_4xBsh4x-tJ6EHTmWh1uH0',
    appId: '1:1083041642321:web:18d420fc515dec1b844570',
    messagingSenderId: '1083041642321',
    projectId: 'my-market-4b747',
    authDomain: 'my-market-4b747.firebaseapp.com',
    storageBucket: 'my-market-4b747.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDP0Gsg088fXj1DRb7vZug2U2Oaxp_F_A',
    appId: '1:1083041642321:android:a1f3aa1da4cb6340844570',
    messagingSenderId: '1083041642321',
    projectId: 'my-market-4b747',
    storageBucket: 'my-market-4b747.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuX7fjZa0xUirU4IzCaSSpkFz4XqUilS8',
    appId: '1:1083041642321:ios:953b7370ab5bd7e8844570',
    messagingSenderId: '1083041642321',
    projectId: 'my-market-4b747',
    storageBucket: 'my-market-4b747.appspot.com',
    iosBundleId: 'com.devnejim.myMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuX7fjZa0xUirU4IzCaSSpkFz4XqUilS8',
    appId: '1:1083041642321:ios:99da75e2d0151937844570',
    messagingSenderId: '1083041642321',
    projectId: 'my-market-4b747',
    storageBucket: 'my-market-4b747.appspot.com',
    iosBundleId: 'com.devnejim.myMarket.RunnerTests',
  );
}
